<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'HipChat' => 'events/lib/HipChat/HipChat.php',
    'HipChat_Exception' => 'events/lib/HipChat/HipChat.php',
    'PhabricatorHipChatEventListener' => 'events/PhabricatorHipChatEventListener.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'HipChat_Exception' => '\\Exception',
    'PhabricatorHipChatEventListener' => 'PhutilEventListener',
  ),
));
